apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullstack-zad2
spec:
  rules:
  - host: zad2.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fullstack-zad2
            port:
              number: 80
